### ISSUE TITLE
why should not use   x += perturb

### ISSUE THREAD

**Issue by yzfxmu** [sangyx/gtrick#1]
Hi, thanks for your work. In FLAG.py, you comment 'add perturb to x, note that do not use x += perturb' in line 65. And I want to know why should not use x += perturb.

**Comment by sangyx** [comment]
Simply, `x += perturb` causes memory leakage in test, because `x += perturb` and `x = x + perturb` act differently in pytorch. You can see <https://crazyoscarchang.github.io/2018/10/04/in-pytorch-not-the-same/> for more details.

**Comment by yzfxmu** [comment]
> Simply, `x += perturb` causes memory leakage in test, because `x += perturb` and `x = x + perturb` act differently in pytorch. You can see https://crazyoscarchang.github.io/2018/10/04/in-pytorch-not-the-same/ for more details.

It's interesting. Thanks for your reply.
