### ISSUE TITLE
 information about the environment

### ISSUE THREAD

**Issue by Elgiva** [sangyx/gtrick#6]
Hi,
Could you plz provide information about the environment in which the code was run (https://github.com/sangyx/gtrick/blob/main/benchmark/pyg/graph_pred.py), including the version of the dependencies used? This will help me to reproduce the results you obtained. Thank you very much.

**Comment by sangyx** [comment]
Hi, the code was run on AWS EC2 p3.8xlarge instance w/ Tesla V100 GPU. I can't remember the version of the dependencies I used. But you can try pyg 2.0.0 because I ran most of the results in April 2022.
